
---
# define intervals and escalations
# in your Check resource
apiVersion: "crd.k8s.afrank.local/v1"
kind: Check
metadata:
  name: check-snippets-admin-ping
  namespace: mozalert-prod
  labels:
    team: mozmeao
    type: pinger
spec:
  check_interval: 3m
  retry_interval: 1m
  notification_interval: 5m
  max_attempts: 3
  image: afrank/pinger
  check_url: https://snippets-admin.us-west.moz.works/admin/
  escalations:
  - type: slack
    env_args:
      webhook_url: "SLACK_DEFAULT_WEBHOOK_URL"
      channel: "SLACK_DEFAULT_CHANNEL"
