---
# define intervals and escalations
# in your Check resource
apiVersion: "crd.k8s.afrank.local/v1"
kind: Check
metadata:
  name: check-firefox-armchair
  namespace: mozalert-prod
  labels:
    team: itse
    type: mozlenium
spec:
  check_interval: 5m
  retry_interval: 3m
  notification_interval: 15m
  max_attempts: 3
  image: afrank/mozlenium
  check_cm: check-firefox-armchair-cm
  escalations:
  - type: slack
    env_args:
      webhook_url: "SLACK_DEFAULT_WEBHOOK_URL"
      channel: "SLACK_DEFAULT_CHANNEL"
  - type: email
      args:
        email: mozalert@mozilla.pagerduty.com
  references:
    source_code: "https://github.com/mozilla-it/itse-apps-prod-2-infra/blob/main/k8s/workloads/checks/mozmeao/check-firefox-armchair.yaml"

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: check-firefox-armchair-cm
  namespace: mozalert-prod
data:
  check.js: |+
    var assert = require('assert');
    $browser.get("http://firefox.com/armchair").then(function(){
        return $browser.getCurrentUrl().then(function(newurl){
            console.log(newurl);
            var pattern = /https:\/\/www.mozilla.org\/en-US\/firefox\/unfck\/\?redirect_source=firefox-com&utm_campaign=unfck&utm_content=podcast&utm_medium=audio&utm_source=armchair/;
            assert(pattern.test(newurl), 'Could not find the pattern ' + pattern + ' in url ' + newurl);
        });
    });
