---
# define intervals and escalations
# in your Check resource
apiVersion: "crd.k8s.afrank.local/v1"
kind: Check
metadata:
  name: check-observatory-frontend-ping
  namespace: mozalert-prod
  labels:
    team: eis
    type: pinger
spec:
  check_interval: 5m
  retry_interval: 3m
  notification_interval: 15m
  max_attempts: 3
  image: afrank/pinger
  check_url: https://sshscan.rubidus.com/
