---
# define intervals and escalations
# in your Check resource
apiVersion: "crd.k8s.afrank.local/v1"
kind: Check
metadata:
  name: check-etherpad-login
  namespace: mozalert-prod
  labels:
    team: itse
    type: mozlenium
spec:
  check_interval: 5m
  retry_interval: 3m
  notification_interval: 15m
  max_attempts: 3
  image: afrank/mozlenium
  secret_ref: mozlenium-shared-secrets
  check_cm: check-etherpad-login-cm
  escalations:
  - type: slack
    env_args:
      webhook_url: "SLACK_DEFAULT_WEBHOOK_URL"
      channel: "SLACK_DEFAULT_CHANNEL"
  references:
    source_code: "https://github.com/mozilla-it/itse-apps-prod-2-infra/blob/main/k8s/workloads/checks/itse/check-etherpad-login.yaml"

---
apiVersion: v1
data:
  check-etherpad.js: |+
    //pad.mozilla.org

    var assert = require('assert');

    $browser.get('https://pad.mozilla.org').then(function () {
      return $browser.waitForAndFindElement($driver.By.xpath('//*[@id="field-email"]'), 10000);
    }).then(function (){
      return $browser.findElement($driver.By.xpath('//*[@id="field-email"]')).sendKeys('moc-sso-monitoring@mozilla.com');
    }).then(function (){
      return $browser.findElement($driver.By.xpath('//*[@id="enter-initial"]')).click();
    }).then(function (){
      return $browser.waitForAndFindElement($driver.By.xpath('//*[@id="field-password"]'), 10000);
    }).then(function (){
      return $browser.findElement($driver.By.xpath('//*[@id="field-password"]')).sendKeys($secure.SSO_LDAP_PASSWORD);
    }).then(function (){
      return $browser.findElement($driver.By.xpath('//*[@id="authorise-ldap-credentials"]')).click();
    }).then(function (){
      return $browser.wait(function() {
      return $browser.getTitle().then(function(title) {
      return title === "Etherpad";
        });
        }, 10000);
    });
kind: ConfigMap
metadata:
  name: check-etherpad-login-cm
  namespace: mozalert-prod
