
---
# define intervals and escalations
# in your Check resource
apiVersion: "crd.k8s.afrank.local/v1"
kind: Check
metadata:
  name: check-dynamicua-origin-ping
  namespace: mozalert-prod
  labels:
    team: itse
    type: pinger
spec:
  check_interval: 3m
  retry_interval: 1m
  notification_interval: 5m
  max_attempts: 3
  escalations:
  - type: slack
    env_args:
      webhook_url: "SLACK_DEFAULT_WEBHOOK_URL"
      channel: "SLACK_DEFAULT_CHANNEL"
  image: afrank/pinger
  check_url: https://dynamicua-origin.mozilla.org/0/%7Baa3c5121-dab2-40e2-81ca-7ea25febc110%7D
