---
# define intervals and escalations
# in your Check resource
apiVersion: "crd.k8s.afrank.local/v1"
kind: Check
metadata:
  name: check-sumo-login
  namespace: mozalert-prod
  labels:
    team: itse
    type: mozlenium
spec:
  check_interval: 5m
  retry_interval: 3m
  notification_interval: 15m
  max_attempts: 3
  image: afrank/mozlenium
  secret_ref: mozlenium-shared-secrets
  check_cm: check-sumo-login-cm
  escalations:
  - type: slack
    env_args:
      webhook_url: "SLACK_DEFAULT_WEBHOOK_URL"
      channel: "SLACK_DEFAULT_CHANNEL"


---
kind: ConfigMap
apiVersion: v1
metadata:
  name: check-sumo-login-cm
  namespace: mozalert-prod
data:
  check-sumo.js: |+
    //support.mozilla.org - search

    /*
     * This will check the amount of search results returned by the main
     * search results page on support.mozilla.org.
     */

    var assert = require('assert');
    var sumo = 'https://support.mozilla.org/en-US/';
    /*
    Search results to check, 1220 results found as of July 2019.
    */
    var searchString = "extensions";
    var expectedResultCount = 1000;

    $browser.get(sumo).then(function(){
      return $browser.waitForAndFindElement($driver.By.id("support-search-masthead"));
    }).then(function(){
      $browser.findElement($driver.By.css("#support-search-masthead> input:nth-child(1)")).sendKeys(searchString).then(function(){
          return $browser.waitForAndFindElement($driver.By.className("sumo-card-heading search-results-heading mb-0")).then(function(element){
              return element.getText().then(function(string){
                console.log("Found string: "+string+"\n");
                var match = string.match(/\d+/);
                console.log("Found result count: "+match+"\n");
                assert(match > expectedResultCount, "No, or not enough, results found for given search ("+string+")");
          })
        })
      });
    });

