---
# define intervals and escalations
# in your Check resource
apiVersion: "crd.k8s.afrank.local/v1"
kind: Check
metadata:
  name: check-firefox-unfck
  namespace: mozalert-prod
  labels:
    team: itse
    type: mozlenium
spec:
  check_interval: 5m
  retry_interval: 3m
  notification_interval: 15m
  max_attempts: 3
  image: afrank/mozlenium
  check_cm: check-firefox-unfck-cm
  escalations:
  - type: slack
    env_args:
      webhook_url: "SLACK_DEFAULT_WEBHOOK_URL"
      channel: "SLACK_DEFAULT_CHANNEL"
  references:
    source_code: "https://github.com/mozilla-it/itse-apps-prod-2-infra/blob/main/k8s/workloads/checks/itse/check-firefox-unfck.yaml"

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: check-firefox-unfck-cm
  namespace: mozalert-prod
data:
  check.js: |+
    var assert = require('assert');
    $browser.get("https://firefox.com/unfck").then(function(){
        return $browser.getCurrentUrl().then(function(newurl){
            console.log(newurl);
            var pattern = /https:\/\/www.mozilla.org\/en-US\/firefox\/unfck.*/;
            assert(pattern.test(newurl), 'Could not find the pattern ' + pattern + ' in url ' + newurl);
        });
    });
