---
# define intervals and escalations
# in your Check resource
apiVersion: "crd.k8s.afrank.local/v1"
kind: Check
metadata:
  name: check-test-login-chrome
  namespace: mozalert-prod
  labels:
    team: itse
    type: mozlenium
spec:
  check_interval: 3m
  retry_interval: 1m
  notification_interval: 15m
  max_attempts: 50
  escalations:
  - type: slack
    env_args:
      webhook_url: "SLACK_DEFAULT_WEBHOOK_URL"
      channel: "SLACK_DEFAULT_CHANNEL"
  image: afrank/mozlenium
  args: [ "chrome" ]
  check_cm: check-test-login-cm

---
# define intervals and escalations
# in your Check resource
apiVersion: "crd.k8s.afrank.local/v1"
kind: Check
metadata:
  name: check-test-login-nightly
  namespace: mozalert-prod
  labels:
    team: itse
    type: mozlenium
spec:
  check_interval: 3m
  retry_interval: 1m
  notification_interval: 15m
  max_attempts: 50
  escalations:
  - type: slack
    env_args:
      webhook_url: "SLACK_DEFAULT_WEBHOOK_URL"
      channel: "SLACK_DEFAULT_CHANNEL"
  image: afrank/mozlenium
  args: [ "firefox" ]
  check_cm: check-test-login-cm

---
# here is the check itself, stored in a configmap
# this block was generated with 
# k create configmap check-test-1-cm --from-file=./demo-check.js
kind: ConfigMap
apiVersion: v1
metadata:
  name: check-test-login-cm
  namespace: mozalert-prod
data:
  demo-check.js: |+
    //demo check

    var assert = require('assert');
    var url = 'https://duckduckgo.com'

    console.log("starting check");

    $browser.get(url).then(function(){
        assert.ok($browser.waitForAndFindElement($driver.By.id("content_homepage"), 30000), "Doesn't seem like things are working properly");
        console.log("well that went great");
    })
