---
# define intervals and escalations
# in your Check resource
apiVersion: "crd.k8s.afrank.local/v1"
kind: Check
metadata:
  name: check-test-ping
  namespace: mozalert-prod
  labels:
    team: itse
    type: pinger
spec:
  check_interval: 3m
  retry_interval: 1m
  notification_interval: 15m
  max_attempts: 50
  image: afrank/pinger
  check_url: https://www.mozilla.org
  escalations:
  - type: slack
    env_args:
      webhook_url: "SLACK_DEFAULT_WEBHOOK_URL"
      channel: "SLACK_DEFAULT_CHANNEL"
