---
# define intervals and escalations
# in your Check resource
apiVersion: "crd.k8s.afrank.local/v1"
kind: Check
metadata:
  name: check-dataviz-login
  namespace: mozalert-prod
  labels:
    team: itse
    type: mozlenium
spec:
  check_interval: 5m
  retry_interval: 3m
  notification_interval: 15m
  max_attempts: 3
  image: afrank/mozlenium
  secret_ref: mozlenium-shared-secrets
  check_cm: check-dataviz-login-cm
  escalations:
  - type: slack
    env_args:
      webhook_url: "SLACK_DEFAULT_WEBHOOK_URL"
      channel: "SLACK_DEFAULT_CHANNEL"


---
kind: ConfigMap
apiVersion: v1
metadata:
  name: check-dataviz-login-cm
  namespace: mozalert-prod
data:
  check-dataviz.js: |+
    //dataviz.mozilla.org - Login
    var assert = require('assert');
    $browser.get('https://dataviz.mozilla.org').then(function () {
      return $browser.waitForAndFindElement($driver.By.xpath('//*[@id="field-email"]'), 60000);
    }).then(function (){
      return $browser.findElement($driver.By.xpath('//*[@id="field-email"]')).sendKeys('moc-sso-monitoring@mozilla.com');
    }).then(function (){
      return $browser.findElement($driver.By.xpath('//*[@id="enter-initial"]')).click();
    }).then(function (){
      return $browser.waitForAndFindElement($driver.By.xpath('//*[@id="field-password"]'), 60000);
    }).then(function (){
      return $browser.findElement($driver.By.xpath('//*[@id="field-password"]')).sendKeys($secure.SSO_LDAP_PASSWORD);
    }).then(function (){
      return $browser.findElement($driver.By.xpath('//*[@id="authorise-ldap-credentials"]')).click();
    }).then(function (){
      return assert.ok($browser.waitForAndFindElement($driver.By.xpath('//*[@id="ng-app"]'), 60000),"Could not load home page correctly");
    });
