---
# define intervals and escalations
# in your Check resource
apiVersion: "crd.k8s.afrank.local/v1"
kind: Check
metadata:
  name: check-sso-login
  namespace: mozalert-prod
  labels:
    team: itse
    type: mozlenium
spec:
  check_interval: 5m
  retry_interval: 3m
  notification_interval: 15m
  max_attempts: 3
  image: afrank/mozlenium
  secret_ref: mozlenium-shared-secrets
  check_cm: check-sso-login-cm
  escalations:
  - type: slack
    env_args:
      webhook_url: "SLACK_DEFAULT_WEBHOOK_URL"
      channel: "SLACK_DEFAULT_CHANNEL"


---
apiVersion: v1
data:
  check-sso.js: |+
    //https://sso.mozilla.com

    var assert = require('assert');
    var user = "moc-sso-monitoring@mozilla.com"
    var url = 'https://sso.mozilla.com'

    $browser.get(url).then(function(){
         $browser.findElement($driver.By.id("field-email")).sendKeys(user).then(function(){
          $browser.findElement($driver.By.id("enter-initial")).click().then(function(){
            $browser.findElement($driver.By.id("field-password")).sendKeys($secure.SSO_LDAP_PASSWORD).then(function(){
              $browser.findElement($driver.By.id("authorise-ldap-credentials")).click().then(function(){
                assert.ok($browser.waitForAndFindElement($driver.By.id("app-grid"), 6000), "Login functionality is not working");

              });
            });
          });
        });
    })
kind: ConfigMap
metadata:
  name: check-sso-login-cm
  namespace: mozalert-prod
