apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: mozlenium-shared-secrets
  namespace: mozalert-prod
spec:
  backendType: gcpSecretsManager
  projectId: mozilla-it-service-engineering
  data:
    - key: itse-apps-prod-2-mozlenium-shared
      version: latest
      name: SSO_LDAP_PASSWORD
      property: SSO_LDAP_PASSWORD
