apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: mozlenium-wiki-secrets
  namespace: mozalert-prod
spec:
  backendType: gcpSecretsManager
  projectId: mozilla-it-service-engineering
  data:
    - key: itse-apps-prod-2-mozlenium-shared
      version: latest
      name: WIKI_USER
      property: WIKI_USER
    - key: itse-apps-prod-2-mozlenium-shared
      version: latest
      name: WIKI_PASSWORD
      property: WIKI_PASSWORD
